In [1]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier # 학습 모델 알고리즘 선택
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

In [3]:
import sklearn
print(sklearn.__version__)

0.23.2


In [4]:
# 간단한 머신러닝 구현

# 1. 데이터 로딩
iris = load_iris()
print(type(iris)) # 데이터프레임 형식이 아니다.

<class 'sklearn.utils.Bunch'>


In [6]:
keys = iris.keys()
print('dataset keys :', keys)

dataset keys : dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [17]:
print('key data\n', iris.data)
print('*' * 50)

print('key target\n', iris.target) # 결과 데이터
print('*' * 50)

print('key target_names\n', iris.target_names)
print('*' * 50)

print('key feature_names\n', iris.feature_names)
print('*' * 50)

print('key DESCR\n', iris.DESCR)
print('*' * 50)

key data
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [

In [18]:
# feature 데이터셋 확인
iris_data = iris.data
iris_data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [21]:
# 레이블(결정값, target, class) 데이터셋 확인
iris_label = iris.target
print(iris_label)
print(iris.target_names)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
['setosa' 'versicolor' 'virginica']


In [25]:
# 데이터 프레임 변환
iris_df = pd.DataFrame(
    data = iris_data,
    columns = iris.feature_names
)

iris_df.head()
iris_df['target'] = iris_label
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [29]:
# 학습 데이터, 테스트 데이터 분리
# 튜플 형식 return -> unpacking
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size = 0.2, random_state = 20)
print('train data :\n', X_train)
print('train label :\n', y_train)
print('test data :\n', X_test)
print('test label :\n', y_test)

train data :
 [[5.7 3.  4.2 1.2]
 [5.6 3.  4.1 1.3]
 [5.1 3.5 1.4 0.2]
 [5.1 3.8 1.6 0.2]
 [4.8 3.4 1.6 0.2]
 [4.9 2.5 4.5 1.7]
 [6.  3.4 4.5 1.6]
 [4.9 3.  1.4 0.2]
 [6.4 3.2 4.5 1.5]
 [7.4 2.8 6.1 1.9]
 [5.7 2.8 4.5 1.3]
 [6.1 2.6 5.6 1.4]
 [4.9 3.6 1.4 0.1]
 [6.7 3.1 4.4 1.4]
 [6.3 3.3 4.7 1.6]
 [4.7 3.2 1.3 0.2]
 [5.4 3.9 1.7 0.4]
 [5.  3.3 1.4 0.2]
 [5.7 2.5 5.  2. ]
 [5.1 3.8 1.9 0.4]
 [6.4 2.8 5.6 2.2]
 [6.2 3.4 5.4 2.3]
 [5.4 3.4 1.5 0.4]
 [6.3 3.3 6.  2.5]
 [6.  2.2 4.  1. ]
 [5.6 2.9 3.6 1.3]
 [5.6 3.  4.5 1.5]
 [4.5 2.3 1.3 0.3]
 [5.1 3.4 1.5 0.2]
 [5.5 2.4 3.8 1.1]
 [6.2 2.9 4.3 1.3]
 [5.8 2.6 4.  1.2]
 [5.6 2.5 3.9 1.1]
 [6.7 3.1 4.7 1.5]
 [6.5 2.8 4.6 1.5]
 [5.7 2.9 4.2 1.3]
 [5.1 3.3 1.7 0.5]
 [6.2 2.2 4.5 1.5]
 [6.3 2.3 4.4 1.3]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.4 3.  4.5 1.5]
 [5.5 2.3 4.  1.3]
 [6.1 3.  4.6 1.4]
 [5.1 3.8 1.5 0.3]
 [5.3 3.7 1.5 0.2]
 [6.4 3.2 5.3 2.3]
 [5.5 3.5 1.3 0.2]
 [4.8 3.1 1.6 0.2]
 [5.  2.  3.5 1. ]
 [6.  3.  4.8 1.8]
 [5.8 2.7 5.1 1.9

In [47]:
# 학습을 위한 학습기 생성 - 알고리즘으로 이루어져있는 객체
iris_dtc = DecisionTreeClassifier(random_state = 20, criterion = 'entropy')
iris_dtc.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=20)

In [48]:
# 예측(Predict) 수행
prediction = iris_dtc.predict(X_test)
print('y_test\n', y_test)
print('prediction\n', prediction)

y_test
 [0 1 1 2 1 1 2 0 2 0 2 1 2 0 0 2 0 1 2 1 1 2 2 0 1 1 1 0 2 2]
prediction
 [0 1 1 2 1 1 2 0 2 0 2 1 1 0 0 2 0 1 2 1 1 2 2 0 1 1 1 0 2 1]


In [49]:
# 예측 정확도 평가
from sklearn.metrics import accuracy_score
print('예측 정확도 : {0:.2f}'.format(accuracy_score(y_test, prediction)))

예측 정확도 : 0.93


In [50]:
# 데이터 프레임 변환
iris_df = pd.DataFrame(
    data = iris_data,
    columns = iris.feature_names
)

iris_df.head()

iris_df['target'] = iris_label
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [54]:
# 데이터 프레임 형식을 나누는 방법
feature_df = iris_df.iloc[:, : -1]
display(feature_df.head())

label_df = iris_df.iloc[:, -1]
display(label_df.head())

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int32

In [67]:
# 학습 데이터, 테스트 데이터 분리
# 튜플 형식 return -> unpacking
X_train, X_test, y_train, y_test = train_test_split(feature_df, label_df, test_size = 0.2, random_state = 11)
print('train data :\n', X_train)
print('train label :\n', y_train)
print('*' * 50)

print('test data :\n', X_test)
print('test label :\n', y_test)
print(type(X_train), type(X_test), type(y_train), type(y_test))

train data :
      sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
120                6.9               3.2                5.7               2.3
122                7.7               2.8                6.7               2.0
49                 5.0               3.3                1.4               0.2
29                 4.7               3.2                1.6               0.2
118                7.7               2.6                6.9               2.3
105                7.6               3.0                6.6               2.1
77                 6.7               3.0                5.0               1.7
36                 5.5               3.5                1.3               0.2
83                 6.0               2.7                5.1               1.6
60                 5.0               2.0                3.5               1.0
131                7.9               3.8          

In [69]:
# 학습을 위한 학습기 생성 - 알고리즘으로 이루어져있는 객체
iris_dtc = DecisionTreeClassifier(random_state = 20, criterion = 'entropy') # random_state : random의 seed와 비슷한 의미
iris_dtc.fit(X_train, y_train)

# 예측(Predict) 수행
prediction = iris_dtc.predict(X_test)

# 예측 정확도 평가
from sklearn.metrics import accuracy_score
print('예측 정확도 : {0:.2f}'.format(accuracy_score(y_test, prediction)))

예측 정확도 : 0.90
