#### (1) 특정 순서로 다차원 배열의 행(row)을 Fancy indexing 하기

In [2]:
import numpy as np

In [5]:
def aryinfo(ary):
    print('type : {}'.format(type(ary)))
    print('shape : {}'.format(ary.shape))
    print('dimension:{}'.format(ary.ndim))
    print('dtype:{}'.format(ary.dtype))
    print('Array Data:\n',ary)

In [6]:
a=np.arange(15).reshape(5,3) # 0부터 14까지 
aryinfo(a)

type : <class 'numpy.ndarray'>
shape : (5, 3)
dimension:2
dtype:int32
Array Data:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [20]:
a[[1,2]]

array([[3, 4, 5],
       [6, 7, 8]])

In [23]:
a[[0,1,4]]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14]])

- 'axis 0' (row 기준)의 아래에서 위 방향(from the end to the first) 으로 fancy indexing을 하고 싶으면 '-' (minus) 부호를 붙여줌
- 단, 이때는 indexing이 '0'부터 시작하는 것이 아니라 '1'부터 시작

In [24]:
a[[-2,-3]]

array([[ 9, 10, 11],
       [ 6,  7,  8]])

#### (2) 특정 순서로 다차원 배열의 행(row)과 열(column)을 Fancy indexing 하기

In [30]:
a[[0,2,4]][:,[0,2]]

array([[ 0,  2],
       [ 6,  8],
       [12, 14]])

####   (3) Fancy Indexing은 view가 아니라 copy 를 생성

In [32]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

# -------------------------------------------------------------------

In [39]:
def aryinfo(ary):
    print('type : {}'.format(type(ary)))
    print('shape : {}'.format(ary.shape))
    print('dimension:{}'.format(ary.ndim))
    print('dtype:{}'.format(ary.dtype))
    print('Array Data:\n',ary)

- 행접근

In [43]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(aryinfo(a))
print('-----')
print(a[[1,2]]) # [[]]안에 번호를 입력하면 특정 행(ROW)를 불러올 수 있다

type : <class 'numpy.ndarray'>
shape : (3, 3)
dimension:2
dtype:int32
Array Data:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
None
-----
[[4 5 6]
 [7 8 9]]


- 행과 열 접근

In [49]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a[[0,1],:][:,[0,2]]

array([[1, 3],
       [4, 6]])

In [53]:
a[[0, 1], :][:, [0, 2]]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [56]:
a[[0, 1], :]

array([[1, 2, 3],
       [4, 5, 6]])

# --------------------------------------------------------------------

In [60]:
A=np.zeros((2,2))
print(A)
print('--------')
B=np.ones((2,2))
print(B)
print('--------')
C=np.eye(2)
print(C)

[[0. 0.]
 [0. 0.]]
--------
[[1. 1.]
 [1. 1.]]
--------
[[1. 0.]
 [0. 1.]]


In [62]:
B+C

array([[2., 1.],
       [1., 2.]])

# -------------------------------------------------------------------

##### Indexing a subset of 1D array : a[from : to]

In [75]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
a[0:5]

array([0, 1, 2, 3, 4])

##### Indexing and Slicing 2D array with comma ',' : d[0:3, 1:3]

- 행과 열 기준으로 위치를 지정해주어서 indexing을 함
- 연속된 위치 값의 경우 '0:2' 처럼 콜론(colon) ':' 를 사용하면 편리함
- 행과 열의 구분은 콤마(comma) ',' 를 사용함.

In [78]:
d=np.arange(20).reshape(4,5)

In [79]:
d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [81]:
d[0]

array([0, 1, 2, 3, 4])

In [82]:
d[0,4] # 첫번째행 다섯번째열 추출

4

In [84]:
d[[0,3]] # [[]]은 행 추출을 의미 : 첫번째 행과 네번째 행 전체를 추출

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [85]:
d[0:3,1:]

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]])

##### Indexing and Slicing 2D array with square bracket '[ ][ ]' : d[0:3][1:3]

In [86]:
d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [88]:
d[0][3]

3

##### Indexing and Slicing of 3D array : e[0, 0, 0:3]

In [89]:
e = np.arange(24).reshape(2, 3, 4)

In [90]:
e

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [91]:
e_idx_0_0_0_2 = e[0, 0, 0:3]

In [92]:
e_idx_0_0_0_2

array([0, 1, 2])

##### 축 하나를 통째로 가져오기( indexing the entire axis by using colon ':')


In [93]:
e

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [94]:
e[0,:,:3]

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])