## 학습 목표
- 배열과 리스트의 차이점
- 배열 생성 다루는 기법
- 기술 통계
- 결과에 대한 분석하는 방법

- 넘파이의 배열은 모든 원소가 같은 자료형이여햐 한다
- resizing  X

- Vector(1차원-배열)-pandas(Series)
- Matrix(2차원-행렬)-pandas(DataFrame) 

- 선형대수(행렬을 이용한 연산 가능)

In [3]:
import numpy as np

- 배열의 차원과 크기, 타입
- ndim, shape, dtype

In [6]:
def aryinfo(ary):
    print('type : {}'.format(type(ary)))
    print('shape : {}'.format(ary.shape))
    print('dimension:{}'.format(ary.ndim))
    print('dtype:{}'.format(ary.dtype))
    print('Array Data:\n',ary)

# 1차원 배열 생성
- array()

In [7]:
oneAry=np.array([0,1,2,3,4,5,6,7,8,9])
aryinfo(oneAry)

type : <class 'numpy.ndarray'>
shape : (10,)
dimension:1
dtype:int32
Array Data:
 [0 1 2 3 4 5 6 7 8 9]


- List vs Array 차이점(Vector operation)

In [8]:
data=[0,1,2,3,4,5,6,7,8,9]
data*2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
result=[]
for d in data:
    result.append(d*2)
result

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [11]:
result2=[d*2 for d in data]
result2

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [13]:
result3=oneAry*2
result3                    #Vector Operation

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

- 벡터 연산은 비교, 산술, 논리연산을 포함하는 모든 수학연산에 적용됨

In [210]:
xAry=np.array([1,2,3])
yAry=np.array([10,20,30])

In [17]:
2 * xAry + yAry

array([12, 24, 36])

In [18]:
xAry == 2

array([False,  True, False])

In [19]:
yAry > 20

array([False, False,  True])

In [20]:
(xAry == 2) &(yAry > 20)

array([False, False, False])

## 2차원 배열 생성

- ndarray(N-dimensional Array)
- 2차원, 3차원(다차원 배열 자료구조)
- 2차원 배열은 행렬(Matrix)
- list of list (2차원 배열)
- list of list of list (3차원 배열)

In [211]:
# 2개의 행과 3개의 열을 가지는 배열을 만든다면?
twoAry=np.array([[1,2,3],[4,5,6]],dtype=np.float64)
aryinfo(twoAry)

type : <class 'numpy.ndarray'>
shape : (2, 3)
dimension:2
dtype:float64
Array Data:
 [[1. 2. 3.]
 [4. 5. 6.]]


In [212]:
# 행의 개수 열의 개수
print(len(twoAry))
print(len(twoAry[0]))
print(len(twoAry[1]))

2
3
3


## 3차원 배열 생성

In [36]:
threeAry=np.array([[[1,2,3,4],
                    [5,6,7,8],
                    [9,10,11,12]],
                  [[1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12]]])
aryinfo(threeAry)

type : <class 'numpy.ndarray'>
shape : (2, 3, 4)
dimension:3
dtype:int32
Array Data:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [43]:
print('dept',len(threeAry)) # 갯수가 몇개인지
print('row',len(threeAry[0])) # 0번째 행에 있는 ROW가 몇개인지
print('row',len(threeAry[1]))
print('row[0] col',len(threeAry[0][0]))

dept 2
row 3
row 3
row[0] col 4


- 요소의 타입을 변경할 때는 astype()

In [47]:
typeChange=threeAry.astype(np.float64)
aryinfo(typeChange)

type : <class 'numpy.ndarray'>
shape : (2, 3, 4)
dimension:3
dtype:float64
Array Data:
 [[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]
  [ 9. 10. 11. 12.]]

 [[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]
  [ 9. 10. 11. 12.]]]


In [48]:
indexAry=np.array([1,2,3,4,5,6,7])
aryinfo(indexAry)

type : <class 'numpy.ndarray'>
shape : (7,)
dimension:1
dtype:int32
Array Data:
 [1 2 3 4 5 6 7]


In [49]:
indexAry[2]

3

In [50]:
indexAry[-1]

7

In [58]:
# twoAry indexing
aryinfo(twoAry)
# 첫번째 행의 첫번째 열
print(twoAry[0,0])
# 두번째 행의 두번째 열
print(twoAry[0,1])
# 마지막 행의 마지막 열 
print(twoAry[-1,-1])

type : <class 'numpy.ndarray'>
shape : (2, 3)
dimension:2
dtype:float64
Array Data:
 [[1. 2. 3.]
 [4. 5. 6.]]
1.0
2.0
6.0


In [71]:
sliceAry=np.array([[1,2,3,4],[5,6,7,8]])
aryinfo(sliceAry)

# 첫번째 행의 전체
print(sliceAry[0, :])

# 두번째 열의 전체
print(sliceAry[:,1])

# 두번쨰 행의 두번째 열부터 끝까지
print(sliceAry[1,1:])

type : <class 'numpy.ndarray'>
shape : (2, 4)
dimension:2
dtype:int32
Array Data:
 [[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4]
[2 6]
[6 7 8]


In [82]:
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])
aryinfo(m)
# 이 행렬에서 값 7을 인덱싱 한다.
print(m[1,2])
# 이 행렬에서 값 17을 인덱싱 한다.
print(m[2,-1])
# 이 행렬에서 배열 [6,7]을 슬라이싱 한다.
print(m[1,1:3])
# 이 행렬에서 배열 [7,12]을 슬라이싱 한다.
print(m[1:,2])
# 이 행렬에서 배열 [[3,4],[8,9]]을 슬라이싱 한다.
print(m[:2,3:])

type : <class 'numpy.ndarray'>
shape : (3, 5)
dimension:2
dtype:int32
Array Data:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
7
14
[6 7]
[ 7 12]
[[3 4]
 [8 9]]


- fancy indexing
- boolean indexing

In [87]:
arr=np.array([0,1,2,3,4,5,6,7,8,9])
aryinfo(arr)
idx=np.array([True,False,True,False,True,False,True,False,True,False])
print(arr[idx])

type : <class 'numpy.ndarray'>
shape : (10,)
dimension:1
dtype:int32
Array Data:
 [0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [88]:
arr % 2 ==0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [89]:
arr[arr % 2 ==0]

array([0, 2, 4, 6, 8])

In [90]:
cntidx=np.array([0,2,4,6,8])
print(arr[cntidx])

[0 2 4 6 8]


In [110]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

aryinfo(x)

# 이 배열에서 3의 배수를 찾아라
print(x[x % 3 == 0])
# 이 배열에서 4로 나누면 1이 남는 수를 찾아라
print(x[x % 4 == 1])
# 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라
#print([(x[x % 3 == 0]) & (x[x % 4 == 1])])

type : <class 'numpy.ndarray'>
shape : (20,)
dimension:1
dtype:int32
Array Data:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 3  6  9 12 15 18]
[ 1  5  9 13 17]


In [112]:

fancyAry=np.arange(0,12,1).reshape(3,4)
aryinfo(fancyAry)
# 10을 가져온다면?
fancyAry[2,2] #인덱싱

type : <class 'numpy.ndarray'>
shape : (3, 4)
dimension:2
dtype:int32
Array Data:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


10

In [113]:
# 6을 가져오고 싶다면?
fancyAry[1:2,2] #슬라이싱

array([6])

In [114]:
fancyAry[1:2,:]

array([[4, 5, 6, 7]])

In [121]:
# 2하고 10을 가져오고 싶다면?
print(fancyAry[[0,2],2])
aryinfo(fancyAry[ [0,2],2])

[ 2 10]
type : <class 'numpy.ndarray'>
shape : (2,)
dimension:1
dtype:int32
Array Data:
 [ 2 10]


In [124]:
print(fancyAry[[0,2],2:3])

[[ 2]
 [10]]


In [147]:
aryinfo(fancyAry)
#펜싱은 배열의 인덱스로 배열을 쓰는것
rowidx=np.array([0,2])
colIdx=np.array([0,2])
print(fancyAry[[rowidx]][:,colIdx])

type : <class 'numpy.ndarray'>
shape : (3, 4)
dimension:2
dtype:int32
Array Data:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  2]
 [ 8 10]]


# 배열 변형(타입,형태)

In [151]:
x= np.array([1,2,3],dtype='U') #U는 유니코드
aryinfo(x)

type : <class 'numpy.ndarray'>
shape : (3,)
dimension:1
dtype:<U1
Array Data:
 ['1' '2' '3']


In [152]:
x[0]+x[1]

'12'

- inf(무한대) vs NaN

In [153]:
np.array([0,1,-1,0]/np.array([1,0,0,0]))

C:\Users\mgk04.DESKTOP-8Q51H2D\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\mgk04.DESKTOP-8Q51H2D\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([  0.,  inf, -inf,  nan])

In [154]:
np.log(0)

C:\Users\mgk04.DESKTOP-8Q51H2D\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf

##### 함수
- zeros, ones
- zeros_like,ones_like (*like는 카피해서 오는것)
- empty
- arange
- linspace,logspace

- zeros : 크기가 정해져 있고 모든 값이 0인 배열을 생성하려면?

In [156]:
z=np.zeros(5)
aryinfo(z)

type : <class 'numpy.ndarray'>
shape : (5,)
dimension:1
dtype:float64
Array Data:
 [0. 0. 0. 0. 0.]


In [158]:
z=np.zeros((2,3),dtype='i')
aryinfo(z)

type : <class 'numpy.ndarray'>
shape : (2, 3)
dimension:2
dtype:int32
Array Data:
 [[0 0 0]
 [0 0 0]]


In [162]:
o=np.ones((2,3,4),dtype='i8') #dtype:int64
aryinfo(o)

type : <class 'numpy.ndarray'>
shape : (2, 3, 4)
dimension:3
dtype:int64
Array Data:
 [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [164]:
o_like=np.ones_like(o,dtype='f')
aryinfo(o_like)

type : <class 'numpy.ndarray'>
shape : (2, 3, 4)
dimension:3
dtype:float32
Array Data:
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [167]:
z_like=np.zeros_like(z)
aryinfo(z_like)

type : <class 'numpy.ndarray'>
shape : (2, 3)
dimension:2
dtype:int32
Array Data:
 [[0 0 0]
 [0 0 0]]


In [169]:
e=np.empty((4,3)) #empty는 비어있는 배열을 만들어줌 #실제값은 아님 주소값1
aryinfo(e)

type : <class 'numpy.ndarray'>
shape : (4, 3)
dimension:2
dtype:float64
Array Data:
 [[0.0078125 0.0078125 0.0078125]
 [0.0078125 0.0078125 0.0078125]
 [0.0078125 0.0078125 0.0078125]
 [0.0078125 0.0078125 0.0078125]]


In [170]:
a=np.arange(10) #10은 size가 된다 0.....n-1
aryinfo(a)      #arange(*) *에 하나만 들어가면 갯수 여러값이 들어가면 범위

type : <class 'numpy.ndarray'>
shape : (10,)
dimension:1
dtype:int32
Array Data:
 [0 1 2 3 4 5 6 7 8 9]


In [171]:
a=np.arange(3,21,2)
aryinfo(a)

type : <class 'numpy.ndarray'>
shape : (9,)
dimension:1
dtype:int32
Array Data:
 [ 3  5  7  9 11 13 15 17 19]


- 전치행렬?  행렬의 행은 열로, 열은 행으로 바꾼 행렬을 의미한다.
- 속성 T
- transpose operation

In [174]:
arr=np.array([[1,2,3],[4,5,6]])
aryinfo(arr)

type : <class 'numpy.ndarray'>
shape : (2, 3)
dimension:2
dtype:int32
Array Data:
 [[1 2 3]
 [4 5 6]]


In [175]:
arr_transpost=arr.T
aryinfo(arr_transpost)

type : <class 'numpy.ndarray'>
shape : (3, 2)
dimension:2
dtype:int32
Array Data:
 [[1 4]
 [2 5]
 [3 6]]


In [177]:
# vector에 transponse 가능할까?
vec=np.arange(10)
aryinfo(vec)

type : <class 'numpy.ndarray'>
shape : (10,)
dimension:1
dtype:int32
Array Data:
 [0 1 2 3 4 5 6 7 8 9]


In [179]:
vec_transpose=vec.T
aryinfo(vec_transpose)

type : <class 'numpy.ndarray'>
shape : (10,)
dimension:1
dtype:int32
Array Data:
 [0 1 2 3 4 5 6 7 8 9]


In [181]:
vec_transpose=vec.reshape(1,10).T
aryinfo(vec_transpose)

type : <class 'numpy.ndarray'>
shape : (10, 1)
dimension:2
dtype:int32
Array Data:
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


- 배열의 원소를 순차적으로 access하고자 한다면?
- for  (Vector,Matrix)
- iterator (internext(),finished 속성을 이용해서 ndarray 모든 요소를 순차적으로 접근 할 수 있다.)

In [207]:
arr=np.array([1,2,3,4,5])

In [184]:
for tmp in arr:
    print(tmp,end=" ")

1 2 3 4 5 

In [185]:
for idx in range(len(arr)):
    print(arr[idx],end=" ")

1 2 3 4 5 

In [208]:
ite=np.nditer(arr,flags=['c_index'])
while not ite.finished:
    print(arr[ite.index] , end=" ")
    ite.iternext()

1 2 3 4 5 

In [190]:
arr=np.array([[1,2,3],[4,5,6]])
aryinfo(arr)

type : <class 'numpy.ndarray'>
shape : (2, 3)
dimension:2
dtype:int32
Array Data:
 [[1 2 3]
 [4 5 6]]


In [204]:
# 2차원 배열에 대한 순차적 접근 코드 작성
# print(arr.shape[0]) : row
# print(arr.shape[1]) : col
    
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        #print(i,j,end=" ")
        print(arr[i,j],end='\t')
    print("\n")

1	2	3	

4	5	6	



In [209]:
ite=np.nditer(arr,flags=['multi_index'])
while not ite.finished:
    print(arr[ite.multi_index] , end=" ")
    ite.iternext()

1 2 3 4 5 